[package]
name = "imgui-knobs"
version = "0.1.0"
authors = ["DGriffin91 <github@dgdigital.net>"]
edition = "2018"

[dependencies]
imgui = "0.6"


[dev-dependencies]
clipboard = "0.5"
glium = { version = "0.29", default-features = true }
imgui-glium-renderer = "0.6"
imgui-winit-support = "0.6"